apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data
  namespace: todoapp
spec:
  storageClassName: hostpath
  persistentVolumeReclaimPolicy: Delete
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/my-pv
